# Lists

In [12]:
# Creating a List with the use of multiple values
List = ["a", "b", "c"]
print("\nList containing multiple values: ")
print(List)
  
# Creating a Multi-Dimensional List(By Nesting a list inside a List)
List2 = [['a', 'b'], ['c']]
print("\nMulti-Dimensional List: ")
print(List2)
  
# accessing a element from the list using index number
print("Accessing element from the list")
print(List[0])
print(List[2])
  
# accessing a element using negative indexing
print("Accessing element using negative indexing")
      
# print the last element of list
print(List[-1])


List containing multiple values: 
['a', 'b', 'c']

Multi-Dimensional List: 
[['a', 'b'], ['c']]
Accessing element from the list
a
c
Accessing element using negative indexing
c


# Tuple 
   Tuples are immutable in nature i.e. once created it cannot be modified.

In [13]:
# Creating a Tuple with the use of Strings
Tuple = ('a', 'b')
print("\nTuple with the use of String: ")
print(Tuple)
      
# Creating a Tuple with the use of list
list1 = [1, 2, 4, 5, 6]
print("\nTuple using List: ")
Tuple = tuple(list1)
  
# Accessing element using indexing
print("First element of tuple")
print(Tuple[0])
  
# Accessing element from last negative indexing
print("\nLast element of tuple")
print(Tuple[-1])


Tuple with the use of String: 
('a', 'b')

Tuple using List: 
First element of tuple
1

Last element of tuple
6


# Set
mutable collection of data that does not allow any duplication

In [14]:
# Creating a Set with a mixed type of values (Having numbers and strings)
Set = set([1, 2, 'a', 4, 'b', 6, 'c'])
print("\nSet with the use of Mixed Values")
print(Set)
  
# Accessing element using for loop
print("\nElements of set: ")
for i in Set:
    print(i, end =" ")
print()
  
# Checking the element using in keyword
print("c" in Set)


Set with the use of Mixed Values
{'c', 1, 2, 'b', 'a', 4, 6}

Elements of set: 
c 1 2 b a 4 6 
True


# String

In [16]:
String = "It can be taught through tough thorough thought though"
print("Creating String: ")
print(String)
      
# Printing First character
print("\nFirst character of String is: ")
print(String[0])
      
# Printing Last character
print("\nLast character of String is: ")
print(String[-1])

Creating String: 
It can be taught through tough thorough thought though

First character of String is: 
I

Last character of String is: 
h


# Dictionary

In [17]:
# Creating a Dictionary
Dict = {'Name': 'abc', 1: [1, 2, 3, 4]}
print("Creating Dictionary: ")
print(Dict)
  
# accessing a element using key
print("Accessing a element using key:")
print(Dict['Name'])
  
# accessing a element using get()
# method
print("Accessing a element using get:")
print(Dict.get(1))
  
# creation using Dictionary comprehension
myDict = {x: x**2 for x in [1,2,3,4,5]}
print(myDict)

Creating Dictionary: 
{'Name': 'abc', 1: [1, 2, 3, 4]}
Accessing a element using key:
abc
Accessing a element using get:
[1, 2, 3, 4]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


# Matrix

In [18]:
import numpy as np
a = np.array([[1,2,3,4],[4,55,1,2],
              [8,3,20,19],[11,2,22,21]])
m = np.reshape(a,(4, 4))
print(m)
  
# Accessing element
print("\nAccessing Elements")
print(a[1])
print(a[2][0])
  
# Adding Element
m = np.append(m,[[1, 15,13,11]],0)
print("\nAdding Element")
print(m)
  
# Deleting Element
m = np.delete(m,[1],0)
print("\nDeleting Element")
print(m)

[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]]

Accessing Elements
[ 4 55  1  2]
8

Adding Element
[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]
 [ 1 15 13 11]]

Deleting Element
[[ 1  2  3  4]
 [ 8  3 20 19]
 [11  2 22 21]
 [ 1 15 13 11]]
